use_frameworks!

platform :ios, '10.0'

target 'EthanNaverMapCluster_Example' do
  pod 'EthanNaverMapCluster', :path => '../'

  target 'EthanNaverMapCluster_Tests' do
    inherit! :search_paths

    
  end
end
